using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace EuCars.Shared.Enums
{
    public enum Brand
    {
        AC,
        Abath,
        Aixam,
        [Display(Name = "Alfa Romeo")]
        Alfa_Romeo,
        Alpina,
        Aro,
        Asia,
        [Display(Name = "Aston Martin")]
        Aston_Martin,
        Audi,
        Austin,
        BMW,
        Bentley,
        Berliner,
        Bertone,
        Borgward,
        Brilliance,
        Bugatti,
        Buick,
        Cadillac,
        Chevrolet,
        Chrysler,
        Citroen,
        Corvette,
        Cupra,
        DS,
        Dacia,
        Daewoo,
        Daihatsu,
        Daimler,
        Datsun,
        Dkw,
        Dodge,
        Dr,
        Eagle,
        FSO,
        Ferrari,
        Fiat,
        Ford,
        Goupil,
        GAZ,
        Geo,
        GMC,
        [Display(Name = "Great Wall")]
        Great_Wall,
        Haval,
        Heinkel,
        Hillman,
        Honda,
        Hummer,
        Hyundai,
        Ifa,
        Infiniti,
        Innocenti,
        Isuzu,
        Iveco,
        JAS,
        Jaguar,
        Jeep,
        Jpx,
        Kia,
        Lada,
        Laforza,
        Lamborghini,
        Lancia,
        [Display(Name = "Land Rover")]
        Land_Rover,
        Landwind,
        Lexus,
        Lifan,
        Lincoln,
        Lotus,
        MG,
        Mahindra,
        Maserati,
        Matra,
        Maybach,
        Mazda,
        McLaren,
        [Display(Name = "Mercedes Benz")]
        Mercedes_Benz,
        Mercury,
        Mg,
        Microcar,
        Mini,
        Mitsubishi,
        Morgan,
        Moskvich,
        Nissan,
        Oldsmobile,
        Opel,
        Perodua,
        Peugeot,
        Pgo,
        Plymouth,
        Polonez,
        Pontiac,
        Prosche,
        Proton,
        Renault,
        [Display(Name = "Rolls Royce")]
        Rolls_Royce,
        Rover,
        SECMA,
        [Display(Name = "SH auto")]
        SH_auto,
        Saab,
        Samand,
        Santana,
        Saturn,
        Scion,
        Seat,
        Shatenet,
        Shuanghuan,
        Simca,
        Skoda,
        Smart,
        [Display(Name = "Ssang yong")]
        Ssang_yong,
        Subaru,
        Suzuki,
        Talbot,
        Tata,
        Tavria,
        Tazzari,
        Tempo,
        Terberg,
        Tesla,
        Tofas,
        Toyota,
        Trabant,
        Triumph,
        Uaz,
        VROMOS,
        VW,
        Volga,
        Volvo,
        Warszawa,
        Wartburg,
        Wiesmann,
        Xinkai,
        Xinshun,
        Yogomo,
        Zastava,
        Zaz
    }
}
